package pojos;
// Generated 2019.05.18. 9:34:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name="phone"
    ,catalog="contacts"
)
public class Phone  implements java.io.Serializable {


     private Integer id;
     private Contact contact;
     private String number;
     private String type;

    public Phone() {
    }

	
    public Phone(Contact contact) {
        this.contact = contact;
    }
    
    
    public Phone(Contact contact, String number, String type) {
       this.contact = contact;
       this.number = number;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contact_id", nullable=false)
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }

    
    @Column(name="number", length=25)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


